### ISSUE TITLE
A20 - Links: Use norm rules to exclude certain 856 41 links from “Link to Resource” type link

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/Primo-releases#3]

**Comment by AGCooper** [comment]
Consider whether this cannot be achieved more easily on the Alma side.

**Comment by AGCooper** [comment]
[url_41_report.xlsx](https://github.com/emory-libraries/Primo-releases/files/2138287/url_41_report.xlsx)

Report of links that do not have strings already excluded by norm rules.

**Comment by AGCooper** [comment]
Used Alma norm rule to take care of the last big chunk "restricted to ...". Reviewed Erin's list and did not find any glaring issues left.

**Comment by laura-ake** [comment]
Alex and Elizabeth - 

Following on conversation with Alex today:

Link to the original analysis by Erin:  

https://emory.box.com/s/25nth6l62lhk3qg1rkwnnej5mmx3ph0g 

Terms in the second part (subfield $3) of Erin's analysis that indicate "not full textness":  

*Abstract
*Appendices
*Appendix
*Errata
*Excerpt
*Page view
*Preliminary pages
*Publisher’s summary
*Selected content
*Summaries
*Summary
*Supplement
*TOC

Elizabeth was going to check the norm rules to see whether any are already excluded (I know we do Table of Contents but not "TOC", I don't think, and I know we added "summary" (lowercased) but not Summaries).  

Then the decision would be whether any that remain are likely to be a recurring problem, and whether to handle via norm rules if volume is large, or through indicator change in Alma (manual, batch change, etc.), or "other" - and communicate with Jessie as needed.  

Like I said today, this is "stretch goal" so if we're not ready to analyze, act, and dispatch it all for this release, is ok to extend into the next.

**Comment by AGCooper** [comment]
I checked all of those terms in the latest url notes report and at most there were 30 occurrences but mainly like 3 or 5 so I think this should now be considered cleaned  up and something that cataloging has to keep an eye on.

**Comment by laura-ake** [comment]
Thanks for running the report.  You're most likely right.  If you like I will take a look tomorrow just to confirm.  Before we close this one out, I think it would be good to report on it to CataWG (including Jessie), and maybe RIL as well, so they're aware of what we've done and what needs to be done/watched for in Alma going forward.  Because new things may pop up next year, you never know...
