### ISSUE TITLE
A21 - Make sure vernacular form (880) of typed subfields in 505 2nd indicator 0 Enhanced TOC are searchable

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/Primo-releases#4]

**Comment by eipeele** [comment]
@AGCooper is there anything I need to do for this?  $t and $r are already searchable based on what I'm seeing in the norm rules.

**Comment by AGCooper** [comment]
Example: 9936564797902486 880 505-00

**Comment by eipeele** [comment]
Staged in Sandbox

**Comment by eipeele** [comment]
examples Laura gave are now searchable
